---
title: "MetaLab report error"
author: Suggestions to imetalabca@gmail.com
date: Report generated @`r Sys.time()`
always_allow_html: TRUE
output:
  html_document:
    fig_width: 10
    fig_caption: TRUE
    toc: TRUE
    toc_depth: 4
    toc_float:
      collapsed: TRUE
      smooth_scroll: TRUE
    number_sections: TRUE
params:  
  error_message: !r NULL ### Manditory; main data input for the report
  #error_render: !r NULL ### Optional; If provided, will do some statistics
  #if_html: TRUE # if you want to pdf or word export, set this as FALSE
---

<style type="text/css">
.main-container {
  max-width: 1400px;
  margin-left: auto;
  margin-right: auto;
}
</style>



```{r logo in html, echo=FALSE}
  htmltools::img(src = "https://raw.githubusercontent.com/ningzhibin/rmdocpu/master/inst/rmd/iMetaReport.png", 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;width:100px;height:100px;')

```


```{r setup, include=FALSE}
# enviroment setup
knitr::opts_chunk$set(echo = FALSE,warning = FALSE, message = FALSE, cache = FALSE, error  = FALSE)

```


# Error message

**  `r params$error_message` **


