
<!-- input: df_intensity_Q100_log10 -->


# PCA Analysis {.tabset .tabset-fade }



```{r PCA, echo =FALSE, error=TRUE }
PCA_result <- prcomp(t(df_intensity_Q100_log10), scale = TRUE)
loading <- as.data.frame(PCA_result$x)
```


## Contribution plot

* Screeplot

```{r echo =FALSE, fig.width= 8,fig.height=4, error=TRUE }

    # screen plot
    factoextra::fviz_screeplot(PCA_result, barcolor = "grey", barfill  = "grey", addlabels = TRUE )
    #rmetalab::PCA_Screeplot_2(PCA_result)
    #plot(PCA_result)
```


* Contribution plot

```{r echo =FALSE, fig.width= 8,fig.height=4, error=TRUE }

factoextra::fviz_contrib(PCA_result, choice = "ind", axes = 1, color = "grey",fill  = "grey")

```

##  `r section_title ` {.tabset .tabset-fade }


### 2D plot

```{r echo =FALSE, fig.width= 8,fig.height=6, error=TRUE }
factoextra::fviz_pca_ind(PCA_result,col.ind = "cos2",# Color by the quality of representation
                        gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
                         repel = TRUE     # Avoid text overlapping
                         )
  
```



### 3D Scatterplot {.tabset .tabset-fade }




```{r echo =FALSE, fig.width= 6,fig.height=6, error=TRUE }
    
    # only for HTML output
    if(params$if_html){
      plot_ly(loading, x = ~PC1, y = ~PC2, z = ~PC3) %>%
      add_markers() %>%
      add_text(text = row.names(loading))

    }
    
  
```




