
<!-- input: df_intensity_Q100_log10 -->


# PCA Analysis {.tabset .tabset-fade }


##  `r section_title ` {.tabset .tabset-fade }


```{r PCA, echo =FALSE, error=TRUE }
PCA_result <- prcomp(t(df_intensity_Q100_log10), scale = TRUE)
loading <- as.data.frame(PCA_result$x)
```


### Screeplot

```{r echo =FALSE, fig.width= 6,fig.height=6, error=TRUE }

    # screen plot
    factoextra::fviz_screeplot(PCA_result)
    #rmetalab::PCA_Screeplot_2(PCA_result)
    #plot(PCA_result)


  
```


### Scatterplot

```{r echo =FALSE, fig.width= 6,fig.height=6, error=TRUE }


  
  factoextra::fviz_pca_ind(PCA_result,col.ind = "cos2",# Color by the quality of representation
                          gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
                           repel = TRUE     # Avoid text overlapping
                           )
  

  factoextra::fviz_contrib(PCA_result, choice = "ind", axes = 1)

  
```

### 3D scatter

```{r echo =FALSE, fig.width= 6,fig.height=6, error=TRUE }
    
    # only for HTML output
    if(params$if_html){
      plot_ly(loading, x = ~PC1, y = ~PC2, z = ~PC3) %>%
      add_markers() %>%
      add_text(text = row.names(loading))

    }
    
  
```




```{r}
  
   if(!is.null(meta_table)){  


    # do pca analysis with meta groupign information

    pca <-PCA_wrapper_prcomp2(data_matrix = as.matrix(df_intensity_log10), data_meta =  meta_table[,c(2,3)], inputation = TRUE)


    # plotting
    print(pca$pca_scree_plot)

      cat("Scree plot ##  shows the performance of the PCA analysis, the more percentage the top procomponets accounts, the better separation")

    print(pca$pca_component_plot)

      cat("2d PCA Component plot ##")

    print(pca$pca_confidence)

      cat("2d PCA Component plot ## with confidence boundaries")

    print(pca$pca_component_plot_kmeans)

      cat("2d PCA Component plot with K-means grouping, which is non-supervised grouping ")

    # pca$pca_component_plot_3d_interactive

  }

```



