
<!-- ## __ input ___DO not change__ -->
<!-- # df_intensity_Q100_log10 -->



# Heatmap Profiling {.tabset .tabset-fade }

## Without Grouping


### Heatmap of Q100 peptides  {.tabset .tabset-fade }

(with 100% presence across experiments)


```{r echo=FALSE, error=TRUE}
# for files of big size, only show limited number of rows (Q100) for the test
# sparsity <- rowSums(df_intensity > 0) # here sparsity is number of valid values in each row
# index_Q100 <- which(sparsity == ncol(df_intensity)) # index_Q100 is the index of Q100 peptide
# df_intensity_Q100 <- df_intensity[index_Q100, , drop = FALSE] # the Q100 peptide intensity matrix
# df_intensity_Q100_log10 <- log10(as.matrix(df_intensity_Q100))

```


#### Simple Heatmap

```{r echo=FALSE, fig.width= 8, fig.height=6, error=TRUE}
# # plot a heatmap of Q100
heatmap(df_intensity_Q100_log10, scale = "none")
```

#### Simple Heatmap with scale

```{r echo=FALSE, fig.width= 8, fig.height=6, error=TRUE}
# # plot a heatmap of Q100
heatmap(df_intensity_Q100_log10, scale = "row")

```



#### Heatmap.2

```{r echo=FALSE, fig.width= 8, fig.height=6, error=TRUE}
gplots::heatmap.2(scale(df_intensity_Q100_log10))

```




```{r}


#matrix_quick_heatmap(df_intensity_Q100_log10, scale = "row")

# d3heatmap::d3heatmap(df_intensity_Q100_log10,show_grid = FALSE, scale = "row")

# pheatmap::pheatmap(df_intensity_Q100_log10,border_color =  NA)
  

# this is for the next section
# 
# if(length(index_Q100) >100){
#   topN = 100
# }else{
#   topN = length(index_Q100)
# }

  

```



### Heatmap of Top 100 Intensity peptides


```{r echo=FALSE, fig.width = 8, fig.height=6, error=TRUE}


```



```{r}
  

#heatmap of top N    # will wrap this to a function

# peptide_sequence_keep <- peptide_sequence[index_Q100] # keep the Q100 pepide sequence 
# df_intensity_Q100$peptide_total_intensity<- rowSums(df_intensity_Q100) # add total intensity column
# df_intensity_Q100$peptide_sequence <- peptide_sequence_keep # add peptide sequnce column
# 
# 
# df_intensity_topN <- dplyr::top_n(df_intensity_Q100, topN, peptide_total_intensity) # top 100 rows
# rownames(df_intensity_topN) <- df_intensity_topN$peptide_sequence # give the row names back
# 
# 
# df_intensity_topN <-df_intensity_topN[, 1: (ncol(df_intensity_topN)-2)] # delete the last 2 column
# df_intensity_topN_log10 <-log10(df_intensity_topN) # log10

  
  
#d3heatmap::d3heatmap(df_intensity_Q100_log10[,-1,drop = FALSE],show_grid = FALSE, color = "RdYlBu", scale = "row")
#pheatmap::pheatmap(df_intensity_topN_log10,border_color =  NA)
#d3heatmap::d3heatmap(df_intensity_topN_log10,show_grid = FALSE,scale = "row") # this also works
  

  
```


