#' wrapper function of rmarkdown::render 
#' 
#'This metareport function provides a way of generating the report on an R server with provided templates, and return the report from a browser or using API. It works as well on the user end as a stand-alone mode. 
#'
#' @param type string, type of the result to generate the report on, one of summary, peptide,protein,taxon, function
#' @param data_file string, file name/path of the summary.txt from maxquant result txt folder, mandatory 
#' @param meta_file string, file name/path of the meta file, optional, a tsv file, generated by MetaLab, 1st columns as sample name, 2nd column as experiment name, 3rd column and after as grouping information. 
#' @param template_version string, can be "stable","develop",or the actual url (usually gist, github, gitlab, but can be anywhere as long as http accessible) for the template file. Default as "stable", will use the local template on server or local test environment in the installed package folder. "develop" is reserved for development test. The templates from the package development path of metareport/inst/rmd, while working dir is metareport/inst. Otherwise, it will try to download the template file from the url. Failed to retrieve from the url, it will use the stable version on the server instead, and passing a message to the output.html.
#' @param output_format sstring, ee output_format in render, default as html, which has interactivity with plotly support
#' @param output_dir string, see output_dir in render, default value as NULL, the same path of the rmarkdown input
#' @param output_file string, the name of the output file, default for html document is output.html
#'
#' @return no direct return value, but write an output.html to the temp session on the opencpu server
#' 
#' @Note depends on a lot of functions in https://github.com/northomics/rmetalab
#' 
#' @seealso \code{\link{render}}
#' @examples
#'
#' metareport(type = "summary",
#'           data_file = system.file("extdata/HGM/final_summary.tsv", package = "metareport"),
#'           meta_file = system.file("extdata/HGM/meta_info.tsv", package = "metareport"),
#'           output_dir =  getwd(), 
#'           output_file = "report_summary.html")
#'           
#'           
#' metareport(type = "peptide",
#'     data_file = system.file("extdata/HGM/final_peptides.tsv",package = "metareport"),
#'     meta_file = system.file("extdata/HGM/meta_info.tsv", package = "metareport"),
#'     output_dir =  getwd(), 
#'     output_file = "report_peptide.html")    
#'     
#'            
#' metareport(type = "protein",
#'     data_file = "extdata/HGM/final_proteins.tsv",
#'     meta_file = "extdata/HGM/meta_info.tsv",
#'     output_dir =  getwd(), 
#'     output_file = "report_protein.html")                   
#'                          
#' metareport(type = "taxon",
#'     data_file = system.file("extdata/HGM/Taxa.tsv", package = "metareport"),
#'     meta_file = system.file("extdata/HGM/meta_info.tsv", package = "metareport"),
#'     output_dir =  getwd(), 
#'     output_file = "report_taxon.html")                                        
#'
#'
#' metareport(type = "function",
#'     data_file = system.file("extdata/HGM/functions_report.tsv", package = "metareport"),
#'     meta_file = system.file("extdata/HGM/meta_info.tsv", package = "metareport"),
#'     output_dir =  getwd(), 
#'     output_file = "report_function.html")
#'
#'
#' @export
#'
#'


metareport <- function(type = "summary", # mandatory
                       data_file, # mandatory
                       meta_file = NULL, 
                       template_version = "stable",  # "develop", "stable", or the url for the template, usually at gist or gitlab, github, )
                       output_format = "html_document", 
                       output_dir = NULL,
                       output_file = "output.html"){
  
  # initialize
  warning_message = NULL # store the message while reading the data tables
  
  # choose the right markdown file as the template to render
  template_file <- switch(type, 
                          "summary" = "ReportTemplate_summary.Rmd",
                          "peptide" = "ReportTemplate_peptide.Rmd",
                          "protein" = "ReportTemplate_protein.Rmd",
                          "taxon" = "ReportTemplate_taxon.Rmd",
                          "function" = "ReportTemplate_function.Rmd",
                          "mismatch_type.Rmd")
  
  template_file_error <- switch(template_version,
                                "stable" = system.file("rmd","error_message.Rmd", package = "metareport") ,
                                "develop" = "rmd/error_message.Rmd"
                                
  ) 
  
  
  ### get the path of the template file
  if (template_version == "stable"){    # use the local copy on the sever or from the local installed version, which is stable version
    template_file_path <- system.file("rmd",template_file, package = "metareport")
  } else if(template_version == "develop" ){# use local development version in development environment
    template_file_path <- paste0("rmd/",template_file)
  }else{# provided as url, download the template from url, cannot really control the quality, will tolerate any error and render anyway
    #myfile <- RCurl::getURL(paste0(url_endpoint,template_version, "/", "MQ_report_summary.Rmd")) # RCurl does not work on windows
    #remote_file <- httr::GET(paste0(url_endpoint,template_version, "/", template_file)) # this need to be tested after
    remote_file <- httr::GET(template_version) #
    
    if( remote_file$status_code == 200){ # if file exists
      writeLines(rawToChar(remote_file$content), con="input.Rmd")
      template_file_path <- "input.Rmd"
    }else{ # use local file if the requested file does not exists
      template_file_path <- system.file("rmd",template_file, package = "metareport")
      warning_message <- 'Template provided could not be retrieved, use the stable version on the server instead!'
    }
  }
  
  # read in data table, if there there is error  no need to continue, 
  # if there is detrimental warnings stopping readiing in the whole table, even conitue, it will not render a full report
  withCallingHandlers(data_table <- rio::import(data_file, check.names = TRUE),
                      
                      warning = function(w){ print("warning triggered!");
                        warning_message <<- c(warning_message,"\n","There is warning messages while reading in the function data file, 
                                              please double check what is going wrong: \n\n", toString(w))
                        rmarkdown::render(template_file_error, 
                                          output_format = output_format, 
                                          params = list(error_message = toString(w)), 
                                          output_dir = output_dir,
                                          output_file = output_file)
                      },
                      
                      error = function(e){print("error triggered, something wrong with the data_table!");
                        rmarkdown::render(template_file_error, 
                                          output_format = output_format, 
                                          params = list(error_message = toString(e)), 
                                          output_dir = output_dir,
                                          output_file = output_file)
                      }
  )
  
  
  # render
  # check the meta_file status before rendering
  
  if(!is.null(meta_file)){ 
    #meta_table <- rio::import(meta_file, header = TRUE, check.names = TRUE, stringsAsFactors = FALSE) # read in the meta table file
    withCallingHandlers(meta_table <- rio::import(meta_file, header = TRUE, check.names = TRUE),
                        error = function(e){
                          warning_message <- c(warning_message,"\n", toString(e), "Conitune without meta information") 
                          rmarkdown::render(template_file_path,
                                            output_format = output_format, 
                                            params = list(data_table =  data_table,  external_message = warning_message), 
                                            output_file = output_file, 
                                            output_dir =  output_dir)
                        }                 
    )
    
    rmarkdown::render(template_file_path,
                      output_format = output_format, 
                      params = list(data_table =  data_table, meta_table = meta_table, external_message = warning_message), 
                      output_file = output_file, 
                      output_dir =  output_dir)
    
    
  }else{
    rmarkdown::render(template_file_path,
                      output_format = output_format, 
                      params = list(data_table =  data_table, external_message = warning_message), 
                      output_file = output_file, 
                      output_dir =  output_dir)
    
  }
  
  invisible()
}









