
#' wrapper function of rmarkdown::render for opencpu to render a report for function.csv
#'
#' This function works on the opencpu server end, to produce an html file, which can then be retrieved by javascript or any other customer api tool.
#' It also works on the stand alone mode, to generate a report file, output.html in the currrent folder, using a public accessible rmd file on github.
#' Of course, this need internect connection to run
#'
#'
#' @param file the file path, string is the tsv file, function.txt
#' @param meta the file (path), optional, string is the tsv file, generated by MetaLab2.0, 1st columns as sample name, 2nd column as experiment name, 3rd column and after as grouping
#'
#' @return no direct return, but write an output.html to the temp session on the opencpu server
#' @seealso \code{\link{render}}  \code{\link{knit}} \code{\link{render_MQsummary}} \code{\link{render_MQsummary_file}} \code{\link{render_proteinGroups_file}}
#' @examples
#'   render_function_file(file = "function.csv")
#'   render_function_file(file = "function.csv", meta = "meta.txt")
#' @export
#'
#'
#'



render_function_file <- function(file, meta = NULL){
  
  #data_table  <- readxl::read_excel(file, sheet = 2) # readin from xl file
  data_table <- read.csv(file, header = TRUE, sep = ",")
  
  myfile <- RCurl::getURL("https://raw.githubusercontent.com/ningzhibin/rmdocpu/master/inst/rmd/ML_report_function.Rmd")
  writeLines(myfile, con="input.Rmd");
  
  if(!is.null(meta)){
    meta_table <- read.delim(meta, header = TRUE, check.names = FALSE, stringsAsFactors = FALSE) # with meta file
    rmarkdown::render("input.Rmd",output_format = "html_document", params = list(input_datatable =  data_table, meta_table = meta_table), output_file="output.html")
    
  }else{
    rmarkdown::render("input.Rmd",output_format = "html_document", params = list(input_datatable =  data_table), output_file="output.html")
  }
  
  invisible()
}


# the rendering function needs to write a temperary file, whether in the same path as the input, or defined by the user
# if the input is on the server, usually the path is not writable, therefore you need to set the intermediate_dir
# an workround way is to read in the file, and write into a temp file. therefore everything is going to be in the temp file

