#' wrapper function of rmarkdown::render for opencpu to render a report for peptides.txt from markdown template
#'
#' This function is destined for working on the opencpu server end, accepting file posted by front end to produce an html file to send to the front end.
#' It also works in  stand-alone mode, to generate a report file, output.html, using a public accessible rmd file on github. Of course, this need internet connection to run
#'
#'
#'
#' @param file string, the file (path) of the peptide.txt, from maxquant result txt folder mandatory 
#' @param meta the file (path), optional, string is the tsv file, generated by MetaLab2.0, 1st columns as sample name, 2nd column as experiment name, 3rd column and after as grouping
#' @param template_version string, can be "latest","stable", or a specific number, like "1.0", "1.1". Default as "stable". Will use the local template in the package (system.file("rmd","MQ_report_summary.Rmd", package = "metareport")), otherwise, it will try to curl the corresponding file from the deposit from either gitlab/github. Besure to use the correct number. If the version defined does not exist, or failed to retrieve from the deposit, it will use the stable version instead.
#' @param output_format see output_format in render
#' @param output_dir see output_dir in render
#' 
#' @return no direct return, but write an output.html to the temp session on the opencpu server
#' @seealso \code{\link{render}}  \code{\link{knit}} \code{\link{render_MQsummary}} \code{\link{render_MQsummary_file}} \code{\link{render_proteinGroups_file}}
#' @examples
#'   datafile <- system.file("extdata","peptide.txt", package = "metareport")
#'   metafile <-system.file("extdata","metainfo.txt", package = "metareport")
#'   
#'   # generate a report without meta information 
#'   render_peptide_file(file = datafile, output_dir =  getwd())
#'   # generate a report with meta information
#    render_MQsummary_file(file = datafile , meta =metafile, output_dir =  getwd())
#' @export
#'
#'
#'

render_peptides_file <- function(file, meta = NULL, template_version = "stable" ,output_format = "html_document", output_dir = NULL){
  
  
  
  
  if (template_version == "stable"){    # use the local one
    local_file_path <- system.file("rmd","MQ_report_peptides.Rmd", package = "metareport")
  } else{
    
    url_deposit <- "https://gitlab.com/iMetaLab/rmdocpu/-/raw/master/" # github was blocked on some servers
    #myfile <- RCurl::getURL(paste0(url_deposit,template_version, "/", "MQ_report_summary.Rmd")) # RCurl does not work on windows
    remote_file <- httr::GET(paste0(url_deposit,template_version, "/", "MQ_report_peptides.Rmd")) #
    
    if( remote_file$status_code == 200){ # if file exists
      writeLines(rawToChar(remote_file$content), con="input.Rmd")
      local_file_path <- "input.Rmd"
    }else{ # use local file if the requested file does not exists
      local_file_path <- system.file("rmd","MQ_report_summary.Rmd", package = "metareport")
    }
    
  }
  
  
  data_table  <- read.delim(file, header = TRUE,check.names = FALSE, stringsAsFactors = FALSE) # NOTE the read in options
  
  myfile <- RCurl::getURL("https://raw.githubusercontent.com/ningzhibin/rmdocpu/master/inst/rmd/MQ_report_peptides.Rmd")
  writeLines(myfile, con="input.Rmd");
  
  if(!is.null(meta)){
    meta_table <- read.delim(meta, header = TRUE, check.names = FALSE, stringsAsFactors = FALSE) #with meta file
    
    rmarkdown::render("input.Rmd",output_format = "html_document", params = list(input_datatable =  data_table, meta_table = meta_table), output_file="output.html")
    
  }else{
    rmarkdown::render("input.Rmd",output_format = "html_document", params = list(input_datatable =  data_table), output_file="output.html")
  }
  
  invisible()
}
